/// <auto-generated>
/// This file has been automatically generated. Do not modify.
/// </auto-generated>
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable RedundantAssignment
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace

using System;
using RegressionGames;
using RegressionGames.StateActionTypes;
using UnityEngine;

public class RGStateEntity_BoardManager : RGStateEntityBase
{
    public static readonly Type BehaviourType = typeof(BoardManager);
    public static readonly string EntityTypeName = "BoardManager";
    public static readonly bool IsPlayer = false;
    public override string GetEntityType()
    {
        return EntityTypeName;
    }

    public override bool GetIsPlayer()
    {
        return IsPlayer;
    }

    public override void PopulateFromMonoBehaviour(MonoBehaviour monoBehaviour)
    {
        var behaviour = (BoardManager)monoBehaviour;
        this["tiles"] = behaviour.GetTileIdentifiers();
    }

    public int[,] tiles => (int[,])this["tiles"];
}